replicaCount: 2

image:
  repository: 058862856673.dkr.ecr.us-east-1.amazonaws.com/final-project-django
  tag: latest
  pullPolicy: Always

containerPort: 8000

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DJANGO_DEBUG: "false"
  DJANGO_ALLOWED_HOSTS: "*"

  POSTGRES_HOST: "final-project-rds.c6d6sq4gsqjo.us-east-1.rds.amazonaws.com"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "dbadmin"
  POSTGRES_DB: "appdb"

secret:
  DJANGO_SECRET_KEY: "lesson-7-secret-key"
  POSTGRES_PASSWORD: "django_password"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70