{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .project }}

  source:
    repoURL: {{ .source.repoURL | quote }}
    targetRevision: {{ .source.targetRevision | quote }}
    path: {{ .source.path | quote }}

    helm:
      valueFiles:
        {{- range .source.helm.valueFiles }}
        - {{ . | quote }}
        {{- end }}

  destination:
    server: {{ .destination.server | quote }}
    namespace: {{ .destination.namespace | quote }}

  syncPolicy:
    automated:
      prune: {{ .syncPolicy.automated.prune }}
      selfHeal: {{ .syncPolicy.automated.selfHeal }}

    syncOptions:
      {{- range .syncPolicy.syncOptions }}
      - {{ . | quote }}
      {{- end }}
---
{{- end }}